on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Vulnerabilities check
    steps:
      - name: Check for vulnerabilities
        id: checks
        uses: maddygoround/secrets-not-allowed@main
        with:
          workspace: ${{ github.workspace }}
      - name: Get results of scan
        run: echo "Scan Results - ${{ steps.checks.outputs.result }}"